title: Muhammad Zaid - Personal Website
author: Muhammad Zaid
email: mxz190024@utdallas.edu
description: > # this means to ignore newlines until "baseurl:"
 Muhammad Zaid's personal website for professional career use.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: Liferafter # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
